services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    volumes:
      - ../../config/adguard:/opt/adguardhome/work
      - ../../config/adguard:/opt/adguardhome/conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8082:80"
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.adguard.rule=Host(`adguard.homelab.bnbhat.com`)"
      - "traefik.http.routers.adguard.entrypoints=web"
      - "traefik.http.routers.adguard.middlewares=adguard-https-redirect"
      - "traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=https"

      - "traefik.http.routers.adguard-secure.rule=Host(`adguard.homelab.bnbhat.com`)"
      - "traefik.http.routers.adguard-secure.entrypoints=websecure"
      - "traefik.http.routers.adguard-secure.tls=true"
      - "traefik.http.routers.adguard-secure.tls.certresolver=digitalocean"

      - "traefik.http.services.adguard.loadbalancer.server.port=80"

    networks:
      - frontend

networks:
  frontend:
    external: true
